### ISSUE TITLE
Lo que hice y lo que hay que hacer

### ISSUE THREAD

**Issue by julian-0** [viegasm/SSL-TP3#1]
1. En scanner.l por cada expresión regular tenemos que devolver su token.

2. Creo que PalabraReservada hay que separarlo en cada palabra así es mas fácil el return.

3. En el main lo único que hice fue el while, mi idea era hacer un switch con la variable _**TOKEN**_ que tiene el valor del token y respecto a ese valor imprimir el mensaje y/o mostrar el token (con yytext).

4. En scanner.l  le meti _%option header-file="archivo.h"_ , esto genera _archivo.h_ que lo incluyo en el main.

5. Para probar todo esto hacen:

   - **flex scanner.l** (se generan _scanner.c_ y _archivo.h_)
   - **gcc -o scanner main.c scanner.c -lfl** (genera _scanner.exe_)
   - **scanner < entrada.txt**

Creo que no me olvido nada ahre seguro que si
Salu2
SKERE

**Comment by alevinas** [comment]
Modo diablo Zuñi
